# Generated by Django 4.2 on 2023-04-19 23:49

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0002_auto_20180627_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="debit_negative_balances",
            field=djstripe.fields.StripeBooleanField(
                default=False,
                help_text="A Boolean indicating if Stripe should try to reclaim negative balances from an attached bank account.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="default_for_currency",
            field=djstripe.fields.StripeBooleanField(
                help_text="Whether this external account is the default account for its currency.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=djstripe.fields.StripeBooleanField(
                help_text="Whether the product is currently available for purchase. Only applicable to products of `type=good`.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shippable",
            field=djstripe.fields.StripeBooleanField(
                help_text="Whether this product is a shipped good. Only applicable to products of `type=good`.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="livemode",
            field=djstripe.fields.StripeBooleanField(
                default=None,
                help_text="Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.",
                null=True,
            ),
        ),
    ]
